name: GitHub Actions Demo

on:
  push:
    branches: 
      - "main"
    paths-ignore: 
      - ".github/**"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Print event trigger
        run: echo "The event that trigger this workflow was ${{ github.event_name }}"

      - name: Print branch name
        run: echo "The current branch is ${{ github.ref }}"

      - uses: actions/checkout@v4

      - name: List all file in repository
        run: tree -a
        
