name: Docker Action
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/actions/hello-world-docker-action/**"
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        id: action
        uses: .github/actions/hello-world-docker-action@main
        with:
          who-to-greet: '@almeidat2'

      - name: Output time
        run: echo "The time was ${{ steps.action.outputs.time }} when the action said hello"
